/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.ui.manager;

import poly.dao.CouponDAO;
import poly.dao.impl.CouponDAOImpl;
import poly.entity.Coupon;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.math.BigDecimal;
import java.time.LocalDate;
import javax.swing.JOptionPane;
public class MaGiamGia1 extends javax.swing.JDialog {

   private CouponDAO couponDAO = new CouponDAOImpl();
    private int currentRow = -1;
    private List<Coupon> couponList;
    
    public MaGiamGia1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
          initComponents();
        setLocationRelativeTo(null);
        fillDiscountTypeComboBox();
        fillToTable();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSelect = new javax.swing.JButton();
        btnDeleteSelected = new javax.swing.JButton();
        btnRemoveSelected = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDiscVaule = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JTextField();
        jComboDisCType = new javax.swing.JComboBox<>();
        btnDellete = new javax.swing.JButton();
        btnRefesh = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Mã Giảm Giá");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CouponID", "Description", "DiscountType", "DiscountValue", "StartDate", "EndDate", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnSelect.setText("Chọn mục");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        btnDeleteSelected.setText("Xóa mục đã chọn");
        btnDeleteSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSelectedActionPerformed(evt);
            }
        });

        btnRemoveSelected.setText("Bỏ chọn mục");
        btnRemoveSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveSelectedActionPerformed(evt);
            }
        });

        jLabel8.setText("Tìm kiếm:");

        btnSearch.setText("Tìm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelect)
                .addGap(36, 36, 36)
                .addComponent(btnDeleteSelected)
                .addGap(27, 27, 27)
                .addComponent(btnRemoveSelected)
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelect)
                    .addComponent(btnDeleteSelected)
                    .addComponent(btnRemoveSelected))
                .addGap(41, 41, 41))
        );

        jTabbedPane1.addTab("Chi tiết", jPanel1);

        jLabel2.setText("CouponID *");

        jLabel3.setText("Description *");

        jLabel4.setText("DiscountType *");

        jLabel5.setText("DiscountValue *");

        jLabel6.setText("StartDate *");

        jLabel7.setText("EndDate *");

        jComboDisCType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnDellete.setText("Xóa");
        btnDellete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelleteActionPerformed(evt);
            }
        });

        btnRefesh.setText("Làm mới");
        btnRefesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeshActionPerformed(evt);
            }
        });

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboDisCType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtDesc))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(5, 5, 5)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDiscVaule, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDellete)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefesh)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtDiscVaule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboDisCType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDellete)
                    .addComponent(btnRefesh))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Chỉnh sửa", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // Chỉ xử lý khi double-click (nhấn 2 lần)
        if (evt.getClickCount() == 2) {
            int row = jTable1.getSelectedRow();
            if (row >= 0 && row < couponList.size()) {
                String id = (String) jTable1.getValueAt(row, 0);
                Coupon c = couponDAO.selectById(id);
                if (c != null) {
                    setForm(c);
                    currentRow = row;
                    
                    // Chuyển sang tab "Chỉnh sửa" để hiển thị thông tin
                    jTabbedPane1.setSelectedIndex(1);
                    
                    // Hiển thị thông báo
                    System.out.println("Double-click: Đã chọn mã giảm giá: " + c.getCouponId() + " - " + c.getDescription());
                    JOptionPane.showMessageDialog(this, 
                        "Đã chọn mã giảm giá: " + c.getCouponId() + "\nMô tả: " + c.getDescription(), 
                        "Thông tin mã giảm giá", 
                        JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        selectAllItems();
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
              try {
                Coupon c = getForm();
                if (couponDAO.selectById(c.getCouponId()) != null) {
                    JOptionPane.showMessageDialog(this, "CouponID đã tồn tại!");
                    return;
                }
                couponDAO.insert(c);
                fillToTable();
                clearForm();
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Lỗi thêm: " + ex.getMessage());
            }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
                Coupon c = getForm();
                if (couponDAO.selectById(c.getCouponId()) == null) {
                    JOptionPane.showMessageDialog(this, "CouponID không tồn tại!");
                    return;
                }
                 couponDAO.update(c);
                fillToTable();
                clearForm();
                JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Lỗi cập nhật: " + ex.getMessage());
            }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDelleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelleteActionPerformed
      int row = jTable1.getSelectedRow();
            if (row < 0) {
                JOptionPane.showMessageDialog(this, "Chọn dòng để xóa!");
                return;
            }
            String id = (String) jTable1.getValueAt(row, 0);
            int confirm = JOptionPane.showConfirmDialog(this, "Xác nhận xóa CouponID: " + id + "?", "Xóa", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    couponDAO.delete(id);
                    fillToTable();
                    clearForm();
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Lỗi xóa: " + ex.getMessage());
                }
            }
    }//GEN-LAST:event_btnDelleteActionPerformed

    private void btnRefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeshActionPerformed
       clearForm();
    }//GEN-LAST:event_btnRefeshActionPerformed

    private void btnDeleteSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSelectedActionPerformed
        deleteSelectedItems();
    }//GEN-LAST:event_btnDeleteSelectedActionPerformed

    private void btnRemoveSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveSelectedActionPerformed
       deselectAllItems();
    }//GEN-LAST:event_btnRemoveSelectedActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String keyword = txtSearch.getText().trim().toLowerCase();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        if (keyword.isEmpty()) {
            // Nếu từ khóa rỗng, hiển thị tất cả
            fillToTable();
            return;
        }
        
        int foundCount = 0;
        for (Coupon c : couponDAO.selectAll()) {
            if (c.getCouponId().toLowerCase().contains(keyword) ||
                (c.getDescription() != null && c.getDescription().toLowerCase().contains(keyword))) {
                model.addRow(new Object[] {
                    c.getCouponId(),
                    c.getDescription(),
                    c.getDiscountType(),
                    c.getDiscountValue(),
                    c.getStartDate(),
                    c.getEndDate(),
                    false
                });
                foundCount++;
            }
        }
        
        // Hiển thị kết quả tìm kiếm
        if (foundCount > 0) {
            JOptionPane.showMessageDialog(this, 
                "Tìm thấy " + foundCount + " kết quả cho từ khóa: '" + keyword + "'", 
                "Kết quả tìm kiếm", 
                JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, 
                "Không tìm thấy kết quả nào cho từ khóa: '" + keyword + "'", 
                "Kết quả tìm kiếm", 
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaGiamGia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaGiamGia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaGiamGia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaGiamGia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MaGiamGia1 dialog = new MaGiamGia1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDeleteSelected;
    private javax.swing.JButton btnDellete;
    private javax.swing.JButton btnRefesh;
    private javax.swing.JButton btnRemoveSelected;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> jComboDisCType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtDiscVaule;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration//GEN-END:variables
private void fillDiscountTypeComboBox() {
        jComboDisCType.removeAllItems();
        jComboDisCType.addItem("Percent");
        jComboDisCType.addItem("Fixed");
    }
   private void fillToTable() {
        couponList = couponDAO.selectAll();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (Coupon c : couponList) {
            model.addRow(new Object[] {
                c.getCouponId(),
                c.getDescription(),
                c.getDiscountType(),
                c.getDiscountValue(),
                c.getStartDate(),
                c.getEndDate(),
                false
            });
        }
        currentRow = -1;
    }
    private void clearForm() {
        txtId.setText("");
        txtDesc.setText("");
        jComboDisCType.setSelectedIndex(0);
        txtDiscVaule.setText("");
        txtStartDate.setText("");
        txtEndDate.setText("");
        currentRow = -1;
        jTable1.clearSelection();
    }
        private Coupon getForm() {
        String id = txtId.getText().trim();
        String desc = txtDesc.getText().trim();
        String type = (String) jComboDisCType.getSelectedItem();
        String valueStr = txtDiscVaule.getText().trim();
        String startStr = txtStartDate.getText().trim();
        String endStr = txtEndDate.getText().trim();
        BigDecimal value = valueStr.isEmpty() ? BigDecimal.ZERO : new BigDecimal(valueStr);
        LocalDate start = startStr.isEmpty() ? null : LocalDate.parse(startStr);
        LocalDate end = endStr.isEmpty() ? null : LocalDate.parse(endStr);
        return new Coupon(id, desc, type, value, start, end);
    }
          private void setForm(Coupon c) {
        txtId.setText(c.getCouponId());
        txtDesc.setText(c.getDescription());
        jComboDisCType.setSelectedItem(c.getDiscountType());
        txtDiscVaule.setText(c.getDiscountValue() != null ? c.getDiscountValue().toString() : "");
        txtStartDate.setText(c.getStartDate() != null ? c.getStartDate().toString() : "");
        txtEndDate.setText(c.getEndDate() != null ? c.getEndDate().toString() : "");
    }
     
        
        /**
         * Chọn tất cả các mục trong bảng
         */
        private void selectAllItems() {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int rowCount = model.getRowCount();
            
            if (rowCount == 0) {
                JOptionPane.showMessageDialog(this, "Bảng không có dữ liệu để chọn!");
                return;
            }
            
            // Chọn tất cả các checkbox
            for (int i = 0; i < rowCount; i++) {
                model.setValueAt(true, i, 6); // Cột 6 là checkbox
            }
            
            // Đếm số mục đã chọn
            int selectedCount = countSelectedItems();
            JOptionPane.showMessageDialog(this, 
                "Đã chọn " + selectedCount + " mục!", 
                "Thông báo", 
                JOptionPane.INFORMATION_MESSAGE);
        }
        
        /**
         * Bỏ chọn tất cả các mục trong bảng
         */
        private void deselectAllItems() {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int rowCount = model.getRowCount();
            
            if (rowCount == 0) {
                JOptionPane.showMessageDialog(this, "Bảng không có dữ liệu!");
                return;
            }
            
            // Bỏ chọn tất cả các checkbox
            for (int i = 0; i < rowCount; i++) {
                model.setValueAt(false, i, 6); // Cột 6 là checkbox
            }
            
            JOptionPane.showMessageDialog(this, 
                "Đã bỏ chọn tất cả mục!", 
                "Thông báo", 
                JOptionPane.INFORMATION_MESSAGE);
        }
        
        /**
         * Xóa các mục đã được chọn
         */
        private void deleteSelectedItems() {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int rowCount = model.getRowCount();
            
            if (rowCount == 0) {
                JOptionPane.showMessageDialog(this, "Bảng không có dữ liệu!");
                return;
            }
            
            // Đếm số mục đã chọn
            int selectedCount = countSelectedItems();
            
            if (selectedCount == 0) {
                JOptionPane.showMessageDialog(this, "Không có mục nào được chọn để xóa!");
                return;
            }
            
            // Xác nhận xóa
            int confirm = JOptionPane.showConfirmDialog(this, 
                "Bạn có chắc chắn muốn xóa " + selectedCount + " mục đã chọn?", 
                "Xác nhận xóa", 
                JOptionPane.YES_NO_OPTION);
                
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    int deletedCount = 0;
                    
                    // Xóa từ cuối lên để tránh lỗi index
                    for (int i = rowCount - 1; i >= 0; i--) {
                        Boolean isSelected = (Boolean) model.getValueAt(i, 6);
                        if (isSelected != null && isSelected) {
                            String couponId = (String) model.getValueAt(i, 0);
                            try {
                                couponDAO.delete(couponId);
                                deletedCount++;
                            } catch (Exception ex) {
                                System.err.println("Lỗi xóa coupon " + couponId + ": " + ex.getMessage());
                            }
                        }
                    }
                    
                    // Refresh bảng
                    fillToTable();
                    clearForm();
                    
                    JOptionPane.showMessageDialog(this, 
                        "Đã xóa thành công " + deletedCount + " mục!", 
                        "Thông báo", 
                        JOptionPane.INFORMATION_MESSAGE);
                        
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, 
                        "Lỗi khi xóa: " + ex.getMessage(), 
                        "Lỗi", 
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
        /**
         * Đếm số mục đã được chọn
         */
        private int countSelectedItems() {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int rowCount = model.getRowCount();
            int count = 0;
            
            for (int i = 0; i < rowCount; i++) {
                Boolean isSelected = (Boolean) model.getValueAt(i, 6);
                if (isSelected != null && isSelected) {
                    count++;
                }
            }
            
            return count;
        }
        
        /**
         * Lấy danh sách các mục đã được chọn
         */
        private java.util.List<String> getSelectedCouponIds() {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int rowCount = model.getRowCount();
            java.util.List<String> selectedIds = new java.util.ArrayList<>();
            
            for (int i = 0; i < rowCount; i++) {
                Boolean isSelected = (Boolean) model.getValueAt(i, 6);
                if (isSelected != null && isSelected) {
                    String couponId = (String) model.getValueAt(i, 0);
                    selectedIds.add(couponId);
                }
            }
            
            return selectedIds;
        }
        

}
