/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poly.ui;

import poly.ui.manager.Doimatkhaudialog;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;

/**
 *
 * @author Nghia
 */
public class KhachJFrame extends javax.swing.JFrame {
   

    /**
     * Creates new form KhachJFrame
     */
    public KhachJFrame() {
        initComponents();
        customizeLayout(); // Thêm hàm này để chỉnh lại giao diện
        // Xóa hiệu ứng hover và các xử lý cho jButton4 vì đã xóa nút này
        addHoverTextEffect(jButton5);
        addHoverTextEffect(jButton6);
        addHoverTextEffect(jButton7);
        addHoverTextEffect(jButton8);
        addHoverTextEffect(jButton9);
        addHoverTextEffect(jButton10);
        // Tự động mở dialog duyệt sản phẩm sau khi giao diện hiển thị
        java.awt.EventQueue.invokeLater(() -> {
            poly.ui.DuyetspJDialog_nghia duyetsp = new poly.ui.DuyetspJDialog_nghia(this, true);
            duyetsp.setLocationRelativeTo(this);
            duyetsp.setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sidebarPanel = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBackground(new java.awt.Color(204, 204, 255));
        headerPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FURNITURE STORE");
        headerPanel.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        sidebarPanel.setBackground(new java.awt.Color(204, 204, 255));
        sidebarPanel.setLayout(new java.awt.GridLayout(7, 1, 0, 5));

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setText("Giỏ hàng");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        sidebarPanel.add(jButton5);

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setText("Thanh toán  ");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        sidebarPanel.add(jButton6);

        jButton7.setBackground(new java.awt.Color(204, 204, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton7.setText("Theo Dõi Đơn Hàng");
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        sidebarPanel.add(jButton7);

        jButton8.setBackground(new java.awt.Color(204, 204, 255));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton8.setText("Hồ sơ ");
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setFocusPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        sidebarPanel.add(jButton8);

        jButton9.setBackground(new java.awt.Color(204, 204, 255));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton9.setText("Đánh giá ");
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setFocusPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        sidebarPanel.add(jButton9);

        jButton10.setBackground(new java.awt.Color(204, 204, 255));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton10.setText("Hỗ trợ ");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setFocusPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        sidebarPanel.add(jButton10);

        jButtonLogOut.setBackground(new java.awt.Color(204, 204, 255));
        jButtonLogOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonLogOut.setText("Đăng xuất");
        jButtonLogOut.setBorder(null);
        jButtonLogOut.setBorderPainted(false);
        jButtonLogOut.setContentAreaFilled(false);
        jButtonLogOut.setFocusPainted(false);
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });
        sidebarPanel.add(jButtonLogOut);

        getContentPane().add(sidebarPanel, java.awt.BorderLayout.LINE_START);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/icon/AnhNenGo.png"))); // NOI18N
        getContentPane().add(jLabel2, java.awt.BorderLayout.CENTER);

        jMenu2.setText("Menu");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customizeLayout() {
        // Sidebar style
        sidebarPanel.setBackground(new java.awt.Color(30, 30, 30));
        sidebarPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 10));
        javax.swing.JButton[] buttons = {jButton5, jButton6, jButton7, jButton8, jButton9, jButton10, jButtonLogOut};
        for (javax.swing.JButton btn : buttons) {
            btn.setBackground(new java.awt.Color(30, 30, 30));
            btn.setForeground(java.awt.Color.WHITE);
            btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
            btn.setBorderPainted(false);
            btn.setFocusPainted(false);
            btn.setContentAreaFilled(false);
        }
        // Không còn nút đầu tiên là Trang Chủ nữa
        // Header style
        headerPanel.setBackground(new java.awt.Color(0, 153, 0));
        headerPanel.setLayout(new java.awt.BorderLayout());
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 28));
        jLabel1.setForeground(java.awt.Color.BLACK);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        // Khởi tạo biến thành viên cho đồng hồ
        timeLabel = new JLabel("", javax.swing.SwingConstants.CENTER);
        timeLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        timeLabel.setForeground(java.awt.Color.BLACK);
        dateLabel = new JLabel("", javax.swing.SwingConstants.RIGHT);
        dateLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));
        dateLabel.setForeground(java.awt.Color.BLACK);
        headerPanel.removeAll();
        headerPanel.add(jLabel1, java.awt.BorderLayout.WEST);
        headerPanel.add(timeLabel, java.awt.BorderLayout.CENTER);
        headerPanel.add(dateLabel, java.awt.BorderLayout.EAST);
        headerPanel.revalidate();
        headerPanel.repaint();
        // Main content background
        getContentPane().setBackground(new java.awt.Color(230, 236, 240));
        // Khởi động timer cập nhật thời gian
        startClock();
        addHoverTextEffect(jButtonLogOut);
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Mở màn hình giỏ hàng
        poly.ui.GioHangJDialog giohang = new poly.ui.GioHangJDialog(this, true);
        giohang.setLocationRelativeTo(this);
        giohang.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // Mở màn hình theo dõi đơn hàng
        poly.ui.TDDonHangJDialog_nghia tddon = new poly.ui.TDDonHangJDialog_nghia(this, true);
        tddon.setLocationRelativeTo(this);
        tddon.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {
      
    }

    // Hiệu ứng hover cho màu chữ JButton
    private void addHoverTextEffect(javax.swing.JButton button) {
        Color originalFg = button.getForeground();
        Color hoverFg = new Color(220, 20, 60); // Đỏ tươi (Crimson)
        button.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                button.setForeground(hoverFg);
            }
            @Override
            public void mouseExited(MouseEvent e) {
                button.setForeground(originalFg);
            }
        });
    }

    // Thêm biến thành viên cho đồng hồ
    private JLabel timeLabel;
    private JLabel dateLabel;

    private void startClock() {
        javax.swing.Timer timer = new javax.swing.Timer(1000, e -> {
            java.time.LocalTime now = java.time.LocalTime.now();
            java.time.LocalDate today = java.time.LocalDate.now();
            java.time.format.DateTimeFormatter dateFmt = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yy");
            timeLabel.setText(now.withNano(0).toString());
            dateLabel.setText(today.format(dateFmt));
        });
        timer.start();
    }

    // Thêm hàm xử lý sự kiện cho nút Đăng Xuất
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
}
